name: grocers
description: "A Grocery Store App."
publish_to: "none"
version: 0.1.0

environment:
    sdk: ">=3.3.0 <4.0.0"

dependencies:
    bloc: ^8.1.4
    equatable: ^2.0.5
    flutter:
        sdk: flutter
    flutter_bloc: ^8.1.5
    get: ^4.6.6
    get_it: ^7.6.8
    google_fonts: ^6.2.1
    intl: ^0.19.0
    path: ^1.9.0
    sqflite: ^2.3.3
    sqflite_common_ffi: ^2.3.3
    sqlite3_flutter_libs: ^0.5.20

dev_dependencies:
    flutter_test:
        sdk: flutter
    flutter_lints: ^3.0.0

flutter:
    uses-material-design: true
    assets:
        - lib/images/
